### ISSUE TITLE
"undefined" error when importing

### ISSUE THREAD

**Issue by joze14rock** [AF-VCD/pdf-bullets#24]
When importing my own Excel abbrs list, then imputing bullets, I receive an "undefined" error in the output. 

EXAMPLE:

input: aircraft
output: acftundefined 

Am I importing it wrong?

**Comment by whurleywhurley** [comment]
Could you post the file you're uploading that has the abbreviations?

**Comment by joze14rock** [comment]
[abbrs.xlsx](https://github.com/AF-VCD/pdf-bullets/files/5066388/abbrs.xlsx)

Attached. Thank you!

**Comment by ckhordiasma** [comment]
All right, from my preliminary troubleshooting there seems to be one or
more abbreviations in your list that cause the abbreviations system to shit
itself. I’ll need to do some more digging in to see which abbreviations are
causing the issue and fix the abbreviations system accordingly.

**Comment by ckhordiasma** [comment]
Ok, on further examination you have several abbreviations like annual(ly) -> ann(ly) and that is causing the problem. 

So there are a couple of issues. 

First, right now my abbreviations system can't handle parentheses on the left side, and it's causing that undefined to show up. This is a bug that I can probably fix. 

Second, the abbreviations list is not smart enough to parse the parentheses into two abbreviations, annual->ann and annually->annly. As a workaround for this, you should make two separate entries for annual and annually. I might make this a new feature but I gotta think carefully about how to implement it without more bugs.

**Comment by joze14rock** [comment]
Sounds good! I'll scrub my abbrv list. Thank you!

**Comment by ckhordiasma** [comment]
fixed in ad7a5f5c656b537cdda0943a99449d2b88a80e58 , will close issue when pulled from my branch (https://ckhordiasma.github.io/pdf-bullets/) into main af-vcd code.

**Comment by ckhordiasma** [comment]
forgot to close this once I merged the fix
