### ISSUE TITLE
Not working on govt computers

### ISSUE THREAD

**Issue by jpdavis60** [AF-VCD/pdf-bullets#32]
Creators,
I just wanted you to know that for some reason I cannot access your program at Eglin afb on govt computer. I need this program! I can't go back to the half space bullshit! It says site cannot be reached, try checking the connection or proxy and the firewall. Y'alls product is the best out there and I need it! Thanks.

John

**Comment by ckhordiasma** [comment]
Can you send a screen capture? Also what link are you using to access the
site?

**Comment by jpdavis60** [comment]
[Image]

I'm working with our IT people to see if it's the firewall blocking it and if it can be added to the approved site list...or however that works. It worked 2 weeks ago though.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ckhordiasma** [comment]
I know some, if not all bases have been switching over from blue coat proxy to just using firewall IP lists. Seems like there's a firewall ip blacklist rule for all *.github.io addresses. 

I have a mirror that works for me on the AFNet, located at master.d3h1nb6qgduyds.amplifyapp.com but note this is built based off my experimental code and might be broken/randomly break in the future.

**Comment by ckhordiasma** [comment]
Wanted to add/recommend, please keep working your comm squadron to see if you can get the domains whitelisted...

**Comment by jpdavis60** [comment]
Oh, I am. Yours is the best product out there. Got multiple snco's that are going to try to get it white listed. Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ckhordiasma** [comment]
I have updates/workarounds for this. 

Easy workaround - 

@smpentecost has graciously mirrored the bullet tool on his site, at http://www.lightningwithinfive.com/AFBS/ . That site should be accessible.

Hard workaround - 

As I mentioned before, this problem started happening when AF bases started transitioning from BlueCoat proxies to Palo Alto Firewall IP Filtering.... Basically the Bluecoat proxies allowed *.github.io, whereas the Palo Alto firewall lists do not by default allow *.github.io. 

Even though the bases have started transitioning away from BlueCoat, the proxies are still there and active, they have just been disabled on most NIPR computers. If you go on your NIPR computer to Internet Options -> Connections Tab -> LAN settings

and re-enable the proxy server/configuration script, you should be able to get back access to the site (until the bluecoat proxies get decommissioned for sure).

**Comment by jpdavis60** [comment]
Copy, I'm gonna try it Monday. I'll be sure to spread the word as well. Thanks for keeping me posted!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ckhordiasma** [comment]
Just checked today, website seems to work on AFNet again! Closing this issue

**Comment by jpdavis60** [comment]
Awesome! Also, the other site you sent seems to be working too. Thanks!!!!!!!!!!!!!
________________________________

**Comment by ckhordiasma** [comment]
Haha, never mind, still definitely blocked on AFNet. Works when I tried through the EURAM VPN but not when directly connected to AFNET.

**Comment by jpdavis60** [comment]
I've been using the lightning within five link

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ckhordiasma** [comment]
I'm going to close this, not sure when it happened but the powers at be in the AFNet have now allowed traffic to the site now.

**Comment by jpdavis60** [comment]
Copy. Thanks

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
