### ISSUE TITLE
word frequency highlighting

### ISSUE THREAD

**Issue by ckhordiasma** [AF-VCD/pdf-bullets#35]
show words that are used multiple times

**Comment by james-craven** [comment]
Any luck implementing this? I actually came here to try to integrate it but I don't know react at all. I got it working in plain vanilla javascript but it's very messy and I'm not that great at clean optimal programming yet. It's hosted at james-craven.github.io/duplicates ... would love to see it integrated to the thesaurus though with a button that toggles the highlights on and off. Would make it so easy and simple to change out the duplicated words.

**Comment by ckhordiasma** [comment]
sorry I completely did not see this question/comment until now haha. Your PR https://github.com/AF-VCD/pdf-bullets/pull/81  is merged now and the feature is on the main site now  

overall great work and I really appreciate it.
