### ISSUE TITLE
Tool freezes and unable to upload acronyms

### ISSUE THREAD

**Issue by kdf12345** [AF-VCD/pdf-bullets#43]
After I paste a bullet, I start deleting letters and the app freezes.  I tried removing all the cookies and cache. This deleted my acronyms so I tried to re import them and it will not import anything, it does not give any error just does not populate. I have tried on multiple web browsers and different workstations. 
I did notice today when I went into the app the input bullet box would shrink down to one line if you deleted everything out which it has never done before.  The bullet I am trying to use is 
- Spearheaded no-notice load change spt; bed down/mobilized 10 anti-radiation wpns f/cmbt msn--armed 5 acft <6 hrs
I delete Spearheaded and Type in Energized and it freezes. It will not freeze at Energize you have to have the d for it to freeze I’m guessing it’s a character count thing, not really sure. 

after the frozen 2 image i get the same fail pop up. 

![Frozen](https://user-images.githubusercontent.com/78821993/107422651-4a376280-6ae9-11eb-89f6-8aa0b38db3d0.png)
![Pop-up](https://user-images.githubusercontent.com/78821993/107422667-4f94ad00-6ae9-11eb-9152-0b8f3c7f105f.png)
![Frozen 2](https://user-images.githubusercontent.com/78821993/107422816-88cd1d00-6ae9-11eb-853b-d5b26ecc496f.PNG)

**Comment by ckhordiasma** [comment]
I'm having trouble recreating the issue. Can you go to save -> JSON and upload the JSON file you have onto this thread?

**Comment by kdf12345** [comment]
I was messing with the app this morning and noticed if I turn off auto-space it does not freeze but when I turn it back on after typing it freezes instantly.  Let me know if you anymore info to help cure this problem. 

[settings.zip](https://github.com/AF-VCD/pdf-bullets/files/5958253/settings.zip)

**Comment by ckhordiasma** [comment]
ah ok, that narrows down things a lot, thanks. For now I reverted the site back to what it was last week, try doing a hard refresh of the page.

**Comment by kdf12345** [comment]
Tried a hard refresh, it fixed the importability of the acronym list but I still have the same problem with the auto-space.

**Comment by ckhordiasma** [comment]
all right, found the bug for the freezing page thing. looking into the spreadsheet thing now.

**Comment by ckhordiasma** [comment]
ok, found and fixed the spreadsheet issue. will be updating site shortly.

**Comment by ckhordiasma** [comment]
ok, should be fixed now. try hard resetting. 

Thanks for reporting the issue and providing detailed instructions for reproducing it! helped a lot.

**Comment by kdf12345** [comment]
Tried it out this morning and it works great.  Thank you for working this issue so fast you saved my week!
