### ISSUE TITLE
Request to have installation and setup steps added to readme

### ISSUE THREAD

**Issue by Matthew-Riddle** [AF-VCD/pdf-bullets#63]
Running into some issues trying to get this up and running. Seems to be a lot of deprecated packages and an issue with mismatched python versions. I fixed that issue but still ran into issues trying to get this up and running. I could be missing something. Could someone possibly add instructions in the readme?

**Comment by ckhordiasma** [comment]
Are you following the instructions in the wiki and then having issues?

**Comment by Matthew-Riddle** [comment]
Ah sorry about that. I did not see that there was a wiki. Found the instructions in the dev section. My bad. Closed

**Comment by ckhordiasma** [comment]
No worries, please lmk if you have any issues!
